version: "3.5"

services:
  db:
    image: postgres:16-alpine
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - 5432:5432

  web:
    build: .
    image: dscorzoni/rinhadjango
    command: >
      sh -c "python rinhadjango/manage.py makemigrations &&
             python rinhadjango/manage.py migrate &&
             python rinhadjango/manage.py initdb &&
             python rinhadjango/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db