# Generated by Django 4.2.10 on 2024-02-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_transaction_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='realizada_em',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
